name: Build PvZ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
            submodules: 'recursive'

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
            cmakeVersion: "3.25.0"

      - name: Configure CMake project
        run: |
            cmake -S . -B build -DCMAKE_INSTALL_PREFIX="./out" -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -A Win32

      - name: Build all projects (including ALL_BUILD)
        run: |
          devenv.com build\PlantsVsZombies.sln \
            /Build "Release|Win32"

      - name: Run INSTALL target to install into out/
        run: |
          devenv.com build\PlantsVsZombies.sln \
            /Project INSTALL \
            /Build "Release|Win32"

      - name: Create artifact
        run: |
          mkdir package
          Compress-Archive -Path out\* -DestinationPath package\LawnProject.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LawnProject
          path: package/LawnProject.zip